### ISSUE TITLE
Size differences between fonts.google.com version

### ISSUE THREAD

**Issue by m4rc1e** [clauseggers/Playfair-Display#4]
*left: this repo | right: fonts.google.com version*
![screen shot 2017-07-10 at 11 17 03](https://user-images.githubusercontent.com/7525512/28013596-7761dfd8-6561-11e7-9649-1fb5d7bc2b7e.png)

Seems the upms are different, this repo 1240 | fonts.google.com 2048

I think we need to retain the same scale for the fonts.google.com version, even if its an error. Users will now be used to this scale. I suggest we add a gen_gf_version.py script so we can create a set fonts for gf which keeps the scaling.

This came about whilst trying to solve, https://github.com/google/fonts/issues/7

cc @davelab6

**Comment by davelab6** [comment]
I'm ok with a new upm if it improves the fonts in some way

What is the thinking behind the new upm?

On Jul 10, 2017 6:23 AM, "Marc Foley" <notifications@github.com> wrote:

*left: this repo | right: fonts.google.com <http://fonts.google.com>
version*
[image: screen shot 2017-07-10 at 11 17 03]
<https://user-images.githubusercontent.com/7525512/28013596-7761dfd8-6561-11e7-9649-1fb5d7bc2b7e.png>

Seems the upms are different, this repo 1240 | fonts.google.com 2048

I think we need to retain the same scale for the fonts.google.com version,
even if its an error. Users will now be used to this scale. I suggest we
add a gen_gf_version.py script so we can create a set fonts for gf which
keeps the scaling.

This came about whilst trying to solve, google/fonts#7
<https://github.com/google/fonts/issues/7>

cc @davelab6 <https://github.com/davelab6>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/clauseggers/Playfair-Display/issues/4>, or mute the
thread

**Comment by clauseggers** [comment]
I don’t remember why the UPM has changed, but it was probably to comply to webfont vertical metrics. I feel we had a discussion about Playfair vertical metrics before, and this was the result.

**Comment by m4rc1e** [comment]
Solved, a script to generate the GF version has been included in the sources dir.

**Comment by RuixiZhang42** [comment]
@clauseggers Hi Claus! I was wondering if the letterforms were actually designed at 1000 UPMs. When using the fonts from this repo, I found the font size “appeared” way too small. For example, the cap height, based on 1240 UPMs, is merely 708/1240 = 57%. As a result, I had to use about 120% of the previous point size in my heading to get Playfair Display to “appear at just the right size”.
